import { ArrowUpRight } from 'lucide-react';
import raw from '../software-campaign-v3.json';

type Score = { applicable?: boolean; pass: number; fail: number; inconclusive: number; denominator: number; lower: number | null; upper: number | null; not_evaluated?: number };
type Row = { id: string; task: string; family: string; method: string; rep: number; status: string; native_calls: number; own_tests: number; elapsed_seconds: number | null; accepted_phases: number | null; native_T9_eligible: boolean; scores: Record<string, Score | null>; full_package: boolean | null; functional_breakdown: { F_valid_success: Score; F_invalid_rejection: Score; F_balanced_valid_invalid_secondary: {lower: number; upper: number} } | null };
type Comparison = { n_blocks: number; mean: {lower: number; upper: number}; scope: string };
type Campaign = { updated_at: string; registered_at: string; planned_cells: number; terminal_cells: number; completed_deliveries: number; eligible_T9: number; F_evaluated: boolean; rows: Row[]; comparisons: Record<string, Comparison>; strata: Record<string, Record<string, Record<string, Comparison>>>; candidate_version: string; candidate_controls: number; candidate_CLI_operations: number; candidate_MCP_operations: number; goal_completed: boolean };
const data = raw as Campaign;
const methods: Record<string,string> = {N:'Trabajo libre', S:'SDD', T:'SpecOrganon', A:'Ablación'};
const statuses: Record<string,string> = {not_started:'Sin iniciar', open:'Sin cierre', complete:'Generación completa', generation_failed:'Fallida', infra_inconclusive:'Infraestructura inconclusa'};
function score(value: Score | null){
  if(!value) return 'Pendiente';
  if(value.applicable===false || value.denominator===0) return 'No aplica';
  if(value.not_evaluated) return 'Sin evaluación';
  return `${value.pass}/${value.denominator}${value.inconclusive ? ` · ${value.inconclusive} inconclusos` : ''}`;
}
function interval(lower: number,upper: number){ return `${(100*lower).toFixed(1)} a ${(100*upper).toFixed(1)} pp`; }
function balanced(value: {lower: number; upper: number}){ return `${(100*value.lower).toFixed(1)} a ${(100*value.upper).toFixed(1)}%`; }

export default function SoftwareCampaign(){
  return <section aria-labelledby="software-campaign-title">
    <h4 id="software-campaign-title">Campaña v3: tres tareas, dos familias de modelos</h4>
    <p>Registrada el {new Date(data.registered_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})}, antes de generar. FractionMix, PolicyPick y ListPatch conservan el orden de las <strong>42 celdas originales</strong>: 12 de trabajo libre, 12 de SDD, 12 de SpecOrganon y 6 de ablación. Codex y Gemini alternan autor y revisor separado, con dos repeticiones por tarea y familia. La ablación conserva borradores de las fases y elimina sus revisiones y compuertas intermedias.</p>
    <div className="backup-counts">{[[String(data.terminal_cells)+'/42','cierres de generación'],[String(data.completed_deliveries),'entregas cerradas'],[String(data.eligible_T9),'entregas T de nueve fases verificadas'],[data.F_evaluated?'Evaluada':'Pendiente','evaluación funcional reservada']].map(([number,label])=><div key={label}><strong>{number}</strong><span>{label}</span></div>)}</div>
    <p>La evaluación reservada requiere cerrar las 42 generaciones y comprobar físicamente los hitos T. Las pruebas propias y las auditorías nativas finales se conservan por separado. <strong>{data.F_evaluated?'El informe muestra resultados del protocolo finito; no prueba corrección universal ni superioridad causal general.':'Todavía no hay puntuaciones funcionales reservadas ni un ganador comparativo.'}</strong> Los fallos de formato, presupuesto y revisión conservan su celda; no se sustituyen.</p>
    <details><summary>Las 42 celdas: estado, recursos y dimensiones</summary><div className="backup-table-wrap"><table><caption>Corte {new Date(data.updated_at).toLocaleString('es-CO',{timeZone:'America/Bogota'})} · F: funcional · D: documentación · G: gobernanza · H: adherencia</caption><thead><tr><th scope="col">Celda / tarea</th><th scope="col">Método / autor</th><th scope="col">Estado</th><th scope="col">Intentos admitidos / pruebas propias</th><th scope="col">F</th><th scope="col">D</th><th scope="col">G</th><th scope="col">H</th><th scope="col">Paquete completo</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><th scope="row">{row.id}<br/>{row.task} · r{row.rep}</th><td>{methods[row.method]}<br/>{row.family}</td><td>{statuses[row.status]}{row.native_T9_eligible?' · T9 verificado':''}</td><td>{row.native_calls} / {row.own_tests}</td>{['F','D','G','H'].map(d=><td key={d}>{d==='H' && row.method==='N' ? 'No aplica' : score(row.scores[d])}</td>)}<td>{row.full_package===null?'Pendiente':row.full_package?'Sí':'No'}</td></tr>)}</tbody></table></div></details>
    <p>Un paquete completo exige conformidad funcional y todos los criterios aplicables de documentación, gobernanza y adherencia. Una generación completa puede fallar parte del contrato reservado. En las generaciones fallidas sin auditoría final, D/G/H conservan la regla de ausencia de evidencia; sus ceros no equivalen a una inspección semántica completa de cada borrador.</p>
    {data.F_evaluated && <details><summary>Entradas válidas e inválidas: diagnóstico funcional</summary><div className="backup-table-wrap"><table><caption>La media equilibrada es secundaria; no sustituye F total ni la exigencia de todas las recetas</caption><thead><tr><th scope="col">Celda / método / autor</th><th scope="col">Entradas válidas</th><th scope="col">Rechazo de inválidas</th><th scope="col">Media equilibrada</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><th scope="row">{row.id} · {row.task}<br/>{methods[row.method]} · {row.family} · r{row.rep}</th><td>{score(row.functional_breakdown?.F_valid_success??null)}</td><td>{score(row.functional_breakdown?.F_invalid_rejection??null)}</td><td>{row.functional_breakdown?balanced(row.functional_breakdown.F_balanced_valid_invalid_secondary):'Pendiente'}</td></tr>)}</tbody></table></div></details>}
    <p>H no se exige a trabajo libre. Los casos contractuales reservados son observaciones del programa; las unidades de comparación son las celdas de autor, tarea, familia y repetición. Se conservan 12 pares T–N, 12 T–S y 6 T–A, además de sus estratos por tarea y familia, sin seleccionar victorias. Los intervalos por resultados desconocidos no son intervalos de confianza.</p>
    {Object.keys(data.comparisons).length>0 && <div className="backup-table-wrap"><table><caption>Diferencias descriptivas apareadas · media de límites en puntos porcentuales</caption><thead><tr><th scope="col">Dimensión y comparación</th><th scope="col">Pares</th><th scope="col">Límites de la media</th></tr></thead><tbody>{Object.entries(data.comparisons).map(([name,value])=><tr key={name}><th scope="row">{name}</th><td>{value.n_blocks}</td><td>{interval(value.mean.lower,value.mean.upper)}</td></tr>)}</tbody></table></div>}
    {Object.entries(data.strata).map(([dimension,groups])=><details key={dimension}><summary>Comparaciones por {dimension==='task'?'tarea':'familia de modelos'}</summary>{Object.entries(groups).map(([identity,comparisons])=><div className="backup-table-wrap" key={identity}><table><caption>{identity} · todos los pares del estrato</caption><thead><tr><th scope="col">Dimensión y comparación</th><th scope="col">Pares</th><th scope="col">Límites de la media</th></tr></thead><tbody>{Object.entries(comparisons).map(([name,value])=><tr key={name}><th scope="row">{name}</th><td>{value.n_blocks}</td><td>{interval(value.mean.lower,value.mean.upper)}</td></tr>)}</tbody></table></div>)}</details>)}
    <h4>Instalación candidata {data.candidate_version}</h4>
    <p>Un checkout separado conserva la campaña congelada. La instalación nueva pasó {data.candidate_controls} controles, verificó los 29 módulos instalados y ejerció {data.candidate_CLI_operations} operaciones de CLI y {data.candidate_MCP_operations} de MCP por stdio real. La extracción produjo 20 páginas y rechazó hashes incorrectos. Los dos builds del wheel fueron idénticos en el mismo entorno fijado. Estos controles usan fixtures y no cuentan como entregas nativas.</p>
    <p>Sobre copias del ledger real se introdujeron perturbaciones sintéticas: una contradicción declarada bloqueó el avance; passed=true sin receipt quedó invalidado; cambiar la premisa dejó 27 descendientes obsoletos y reabrió validación. Restaurar el texto no recuperó las aceptaciones. El original permaneció intacto. Esto comprueba las compuertas ante objeciones explícitas, sin demostrar detección semántica automática. La instalación también verificó replay y reanudación tras SIGKILL.</p>
    <p>El Docker de Codex se construyó también desde el ZIP extraído y pasó su smoke MCP con 24 herramientas, paridad CLI/MCP, rechazo de escrituras obsoletas y persistencia. Conserva un perfil nuevo sin autenticar, separado del experimento activo. Codex CLI es 0.160.0; el smoke no llama a modelos. Desde otra carpeta, Compose necesita -f con la ruta absoluta a compose.yaml.</p>
    <p>Los intentos admitidos incluyen fallos de preparación y no equivalen a llamadas exitosas del proveedor. Los contadores declarados por cada proveedor {data.F_evaluated?'se conservan en el informe con':'se publicarán con'} sus categorías originales. Tokens normalizados, facturación y coste monetario siguen desconocidos. El modo local conserva un mandato declarado; no autentica identidad ni custodia externa. La eficacia de campo y la tesis general no están demostradas.</p>
    <div className="software-lab-downloads"><a className="text-link" href="/resultados/software/campana-v3.json">Campaña v3 · datos y límites<ArrowUpRight size={15}/></a></div>
  </section>;
}
