"""Presentation from the complete immutable report only; no model/subject calls."""
from pathlib import Path
import json,statistics,datetime,hashlib
base=Path(__file__).parent;run=base.parent/'software-comparison-v3';path=run/'report.json'
if not path.exists():raise SystemExit('No immutable original report: no summary is written.')
raw=path.read_bytes();report=json.loads(raw);assert report['evaluation_complete'] is True and report['design_denominator']==42 and len(report['cells'])==42
rows=report['cells'];methods={}
for m in 'NSTA':
 cells=[r for r in rows if r['method']==m];expected=6 if m=='A' else 12;assert len(cells)==expected
 scores={}
 for dimension in ['F','D','G','H']:
  if dimension=='H' and m=='N':scores[dimension]={'applicable':False,'mean':None,'native_cells':12};continue
  values=[r['functional']['F_total'] if dimension=='F' else r['qualitative']['scores'][dimension] for r in cells]
  assert all(type(v['lower']) in (int,float) and type(v['upper']) in (int,float) for v in values)
  scores[dimension]={'applicable':True,'mean':{k:statistics.mean(v[k] for v in values) for k in ['lower','upper']},'native_cells':len(cells),'recipe_or_point_counts':{k:sum(v[k] for v in values) for k in ['pass','fail','inconclusive','denominator']},'scope':'mean per fixed author cell; recipes/points not independent native replicates'}
 methods[m]={'cells':len(cells),'generation_complete':sum(r['generation_status']=='complete' for r in cells),'generation_failed':sum(r['generation_status']=='generation_failed' for r in cells),'generation_inconclusive':sum(r['generation_status']=='infra_inconclusive' for r in cells),'full_packages':sum(r['full_package'] for r in cells),'scores':scores,'mean_elapsed_seconds':statistics.mean(r['resources']['elapsed_seconds'] for r in cells),'native_attempts':sum(r['resources']['admitted_native_attempts'] for r in cells),'own_tests':sum(r['resources']['admitted_own_tests'] for r in cells),'normalized_tokens':None,'monetary_cost':None}
summary={'schema':1,'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'registration_sha256':report['registration_sha256'],'original_report_sha256':hashlib.sha256(raw).hexdigest(),'design_denominator':42,'methods':methods,'all_fixed_paired_comparisons':report['comparisons'],'strata':report['strata'],'scope':'descriptive finite pipeline comparison; no confidence interval/p-value or field causal claim','tokens_and_money_unknown':True,'field_or_general_thesis_proven':False,'goal_completed':False,'published':False}
(base/'web/public/resultados/software/campana-v3-resumen.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
lines=['# SpecOrganon: informe del hito local de software','','Este informe conserva las 42 celdas originales y todos los resultados del protocolo finito. Las unidades de comparación son las celdas de autor, tarea, familia y repetición; los casos contractuales son observaciones del programa. No acredita superioridad causal general, eficacia alimentaria de campo ni la tesis general.','','| Método | Celdas | Entregas cerradas | Paquetes completos | F, media por celda | D | G | H | Tiempo medio |','| --- | ---: | ---: | ---: | --- | --- | --- | --- | --- |']
def percent(score):
 if not score['applicable']:return 'No aplica'
 mean=score['mean'];return f'{100*mean["lower"]:.1f} a {100*mean["upper"]:.1f}%'
for m,name in [('N','Trabajo libre'),('S','SDD'),('T','SpecOrganon'),('A','Ablación')]:
 r=methods[m];lines.append(f'| {name} | {r["cells"]} | {r["generation_complete"]} | {r["full_packages"]} | '+ ' | '.join(percent(r['scores'][d]) for d in ['F','D','G','H'])+f' | {r["mean_elapsed_seconds"]/60:.2f} min |')
lines+=['','F es funcionalidad; D, documentación; G, gobernanza; H, adherencia al procedimiento. H no se exige a trabajo libre. Los límites debidos a datos inconclusos no son intervalos de confianza. Las medias no ponderan una celda de autor más por tener más recetas.','','## Diferencias apareadas originales','','| Dimensión y comparación | Pares | Media de límites, pp |','| --- | ---: | --- |']
for name,r in report['comparisons'].items():lines.append(f'| {name} | {r["n_blocks"]} | {100*r["mean"]["lower"]:.1f} a {100*r["mean"]["upper"]:.1f} |')
lines+=['','Los estratos completos por tarea y familia están en el informe y los datos públicos. Se conservan 12 pares T–N, 12 T–S y 6 T–A; H–N no se calcula. No se seleccionan victorias ni se sustituyen fallos.','','## Alcance y reproducibilidad','','Los fallos de formato y presupuesto pertenecen al conjunto de método, prompt y ejecutor registrado. Una respuesta descartada no se convierte retrospectivamente en entrega, aunque contenga código. Los programas parciales sellados se evaluaron según el protocolo; el programa ausente falla por contrato sin invocar un sujeto. Las puntuaciones semánticas proceden del auditor nativo separado; los localizadores y hashes no autentican por sí solos la verdad o identidad externa.','','Los intentos admitidos incluyen errores anteriores a una llamada exitosa del proveedor y no equivalen a solicitudes facturadas. Los contadores de uso declarados se mantienen por trabajo y proveedor. Tokens normalizados, facturación y coste monetario permanecen desconocidos. Los tiempos corresponden a las ejecuciones registradas y no aíslan exclusivamente el coste del método.','','La campaña original se reanudó tras una lectura fallida de cuota. La reparación afectó al observador privado, sin modificar fuentes registradas, respuestas, modelos, cuentas ni presupuestos; los relojes siguieron desde la admisión original. Las otras lecturas fallidas usaron sólo una observación original aún válida, conservando su fecha real.','','La separación física del evaluador y los roles se verificó en Docker, con entradas y salidas acotadas. Los perfiles originales son un límite de confianza del operador: no se acredita aislamiento absoluto de toda configuración ni desactivación absoluta de herramientas internas de Gemini.','','El candidato rc2 pasó los controles de instalación, CLI/MCP y PDF con hashes fijados. El Docker Codex pasó también desde el ZIP extraído. Los controles de perturbación y SIGKILL usan contenido sintético identificado, sin contar como nuevos casos nativos.','','El paquete de evidencia contiene fuentes congeladas, las 42 entregas y snapshots originales, los 3500 resultados y un extracto de recibos físicos. Reanaliza sus diferencias sin modelos ni nuevos sujetos. Los perfiles, credenciales, cuotas privadas y journals nativos completos se conservan fuera del paquete; la custodia tiene el límite del operador y del sistema de archivos. La generación independiente necesita un registro nuevo, sin continuar o reparar el original.','','Los 30 inputs y resultados del piloto backup, CSVShape, LotLedger y las campañas históricas permanecen intactos. El cierre del hito depende de la entrega y evaluación definidas, aunque sus resultados sean adversos. La verificación de publicación se documenta por separado.']
(base/'web/public/resultados/software/campana-v3-informe.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'summary_written':True,'cells':42,'source_report_sha256':summary['original_report_sha256'],'new_subjects':0,'new_models':0}))
