import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from 'motion/react';
import { ArrowDown, ArrowDownRight, ArrowRight, ArrowUpRight, BookOpen, Bot, Boxes, Braces, Check, ChevronDown, CircleCheck, CodeXml, Command, Database, FileText, GitBranch, Layers3, Menu, Network, ShieldCheck, Terminal, UserRound, Workflow, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import dataJson from './project-data.json';
import type { ProjectData } from './types';
import { fronts, principles } from './content';
import { Count, Logo, RepoLink, Reveal, SectionHead } from './components/Shared';
import HeroGraph from './components/HeroGraph';
import MethodExplorer from './components/MethodExplorer';
import TraceLab from './components/TraceLab';
import GettingStarted from './components/GettingStarted';
import Evidence from './components/Evidence';
import BackupResults from './components/BackupResults';

const data=dataJson as unknown as ProjectData;
const nav=[{id:'metodo',label:'El método'},{id:'trazabilidad',label:'Trazabilidad'},{id:'toolkit',label:'Toolkit'},{id:'empezar',label:'Empezar'},{id:'resultados',label:'Resultados'}];
const questions=[
  {title:'¿Qué propone SpecOrganon frente a SDD?',text:'Integra el trabajo anterior y posterior a la especificación: formular el problema y sus compromisos, investigar con evidencia, comparar alternativas y validar el resultado con criterios previos. SDD es parte de ese recorrido. El proyecto se inspira en Spec Kit.'},
  {title:'¿El toolkit investiga y ejecuta pruebas por sí solo?',text:'El agente aporta el razonamiento y opera las herramientas. CLI, MCP y runner conservan artefactos y pasos declarados y comprueban compuertas. El motor no lanza por sí solo investigación, agentes ni comandos de prueba: el ejecutor conserva los recibos y streams reales.'},
  {title:'¿Quién toma las decisiones normativas?',text:'La persona competente dentro del alcance del encargo. El modo local registra el mandato que ya existe; no crea un permiso nuevo. Las decisiones que excedan ese mandato vuelven al dueño. La política signed exige las firmas y el registro de confianza del contrato correspondiente.'},
  {title:'¿Se puede usar fuera de la alimentación?',text:'Se puede aplicar a otros dominios. El piloto de backups ya construyó un producto fuera de la alimentación y comparó N/S/T con 18 ejecuciones reales. Ese resultado no acredita generalización: solo una familia de tareas, pocas repeticiones y aplicación incompleta del método. El informe conserva estos límites junto a la valoración previa del responsable.'},
  {title:'¿Cómo se retoma un caso y qué pasa si cambia una premisa?',text:'El ledger conserva el checkpoint. Repetir el mismo manifiesto omite los pasos ya materializados. Una referencia nueva puede volver obsoletas las dependencias y reabrir fases. La reparación requiere versiones nuevas y revisión vigente, conservando el historial anterior.'},
  {title:'¿Cuál es el estado actual del estándar?',text:'El toolkit dispone de un MVP técnico local y el piloto autónomo de backups está terminado, con producto, datos y fuentes descargables. La comparación muestra una señal funcional favorable a T, pero no demuestra la tesis general ni aplicación completa del método. La valoración previa C1–C5 del responsable y los casos del 1 de octubre se conservan como antecedentes, con su alcance. La nueva goal de software sigue activa: el entorno Docker fijado reproduce el extractor histórico y pasó controles pertinentes, mientras LogLens y IntervalDesk quedaron inconclusos, sin entrega. La instalación limpia CLI/MCP está comprobada; no se afirma que la suite completa o la tesis estén cerradas.'},
];

export default function App(){
  const [menu,setMenu]=useState(false),[active,setActive]=useState(''),reduced=useReducedMotion();
  const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:140,damping:30,restDelta:.001});
  useEffect(()=>{
    if(!window.location.hash)return;
    const frame=requestAnimationFrame(()=>document.getElementById(window.location.hash.slice(1))?.scrollIntoView({behavior:'instant',block:'start'}));
    return()=>cancelAnimationFrame(frame);
  },[]);
  useEffect(()=>{
    const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)setActive(entry.target.id);});},{rootMargin:'-15% 0px -60% 0px'});
    nav.forEach(item=>{const node=document.getElementById(item.id);if(node)observer.observe(node);});
    return ()=>observer.disconnect();
  },[]);
  useEffect(()=>{if(!menu)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenu(false);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[menu]);
  return <>
    <a href="#inicio" className="skip-link">Ir al contenido</a>
    <motion.div className="reading-progress" style={{scaleX:reduced?scrollYProgress:progress}}/>
    <header className="site-header"><div className="header-inner"><Logo/><nav aria-label="Navegación principal">{nav.map(item=><a key={item.id} href={`#${item.id}`} className={active===item.id?'active':''}>{item.label}{active===item.id&&<motion.span layoutId="nav-active" className="nav-active" transition={{type:'spring',stiffness:300,damping:30}}/>}</a>)}</nav><div className="header-actions"><RepoLink className="header-repo">GitHub</RepoLink><a className="header-start" href="#empezar">Guía de uso<ArrowRight size={13}/></a><button className="mobile-menu-button" onClick={()=>setMenu(!menu)} aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} aria-controls="mobile-navigation">{menu?<X size={20}/>:<Menu size={20}/>}</button></div></div>
      <AnimatePresence>{menu&&<motion.nav id="mobile-navigation" className="mobile-nav" initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} aria-label="Navegación móvil">{nav.map(item=><a key={item.id} href={`#${item.id}`} onClick={()=>setMenu(false)}>{item.label}<ArrowUpRight size={14}/></a>)}<a href="#evidencia" onClick={()=>setMenu(false)}>Estado y evidencia<ArrowUpRight size={14}/></a></motion.nav>}</AnimatePresence>
    </header>
    <main>
      <section className="hero" id="inicio"><div className="hero-grid-background" aria-hidden="true"/><div className="hero-inner"><div className="hero-edition"><span><span className="edition-dot"/>PROPUESTA DE ESTÁNDAR OPERATIVO</span><span>VERSIÓN DE DESARROLLO · PILOTO REAL</span></div><div className="hero-layout"><div className="hero-content"><motion.a href="#resultados" className="hero-release" initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.6}}><CircleCheck size={13}/><span>Piloto autónomo publicado · 18 ejecuciones</span><ArrowUpRight size={12}/></motion.a><motion.h1 initial={reduced?false:{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.9,delay:.1,ease:[.22,1,.36,1]}}>De la pregunta<br/>a una intervención<br/><em>con razones.</em></motion.h1><motion.p className="hero-intro" initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.25}}>Filosofía, ciencia e ingeniería conectadas por un método que hace explícito <strong>qué se decide, por qué y cómo se comprueba.</strong></motion.p><motion.div className="hero-cta" initial={reduced?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.75,delay:.4}}><a href="#empezar" className="button hero-primary">Usar el método<ArrowRight size={16}/></a><a href="#metodo" className="hero-secondary">Explorar las nueve fases<ArrowDown size={14}/></a></motion.div><motion.div className="hero-qualities" initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{duration:.7,delay:.6}}><span><Check size={11}/>Artefactos versionados</span><span><Check size={11}/>Contexto reanudable</span><span><Check size={11}/>Revisión explícita</span></motion.div></div><HeroGraph/></div><div className="hero-stats">{[{value:data.phases.length,label:'Fases con contratos',note:'Propósito, evidencia y compuertas'},{value:fronts.length,label:'Frentes conectados',note:'De la formulación a la validación'},{value:data.mvp.tools.length,label:'Herramientas MCP',note:'Descubiertas en el wheel instalado'},{value:data.mvp.cases.length,label:'Casos locales completos',note:'Nueve fases por proyecto'}].map(item=><div key={item.label}><strong><Count value={item.value}/></strong><div><span>{item.label}</span><small>{item.note}</small></div></div>)}</div></div></section>

      <section className="section premise-section" id="proyecto"><SectionHead number="01" eyebrow="QUÉ ES SPECORGANON" title="Las soluciones necesitan" accent="una justificación completa." description="Una metodología operativa y un toolkit reutilizable, inspirado en Spec Kit. El recorrido incorpora la constitución del problema, el estudio científico, la especificación y la validación de una intervención."/><div className="principles-grid">{principles.map((item,index)=>{const Icon=item.icon;return <Reveal key={item.title} delay={index*.05} className="principle-card"><div className="principle-top"><span>{String(index+1).padStart(2,'0')}</span><Icon size={22}/></div><h3>{item.title}</h3><p>{item.text}</p></Reveal>;})}</div><Reveal className="sdd-extension"><div className="sdd-extension-label"><Workflow size={18}/><span>UN RECORRIDO MÁS AMPLIO</span></div><div><span>Problema</span><ArrowRight size={13}/><span>Investigación</span><ArrowRight size={13}/><strong>SDD</strong><ArrowRight size={13}/><span>Intervención</span><ArrowRight size={13}/><span>Validación</span></div><p>La especificación queda ligada a las razones que la originaron y a la evidencia que podrá sostener su resultado.</p></Reveal></section>
      <MethodExplorer phases={data.phases}/>
      <TraceLab/>
      <Toolkit tools={data.mvp.tools}/>
      <GettingStarted phases={data.phases}/>
      <Evidence data={data}/>
      <BackupResults/>
      <section className="section questions-section" id="preguntas"><SectionHead number="08" eyebrow="ENTENDER EL ALCANCE" title="Las preguntas" accent="también son parte del método."/><div className="questions-grid"><Reveal className="questions-aside"><BookOpen size={26}/><h3>Un estándar que<br/><em>puede revisarse.</em></h3><p>Explicitar premisas, conservar hallazgos adversos y delimitar el veredicto hace posible volver sobre una decisión sin perder su historia.</p><a href="#metodo" className="text-link">Volver a los contratos<ArrowUpRight size={14}/></a></Reveal><div className="faq-list">{questions.map((item,index)=><Reveal key={item.title} delay={index*.025}><details><summary>{item.title}<ChevronDown size={16}/></summary><p>{item.text}</p></details></Reveal>)}</div></div></section>
      <section className="section sources-section" id="fuentes"><SectionHead number="09" eyebrow="EL PROYECTO, CONSULTABLE" title="El método y su desarrollo," accent="en su contexto." description={data.scope}/><Reveal className="publication-note"><FileText size={17}/><div><strong>Fuentes y avances publicados en main</strong><p>{data.repository_revision_note}</p><span>BASE DOCUMENTAL HISTÓRICA {data.reviewed_head} · {new Date(data.published_at).toLocaleString('es-CO',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})} UTC</span></div></Reveal><Reveal><details className="sources-details"><summary>Documentos que sustentan esta presentación<ArrowDownRight size={17}/></summary><div>{data.sources.map(item=><div className="source-row" key={item.path}><div>{item.url?<a href={item.url} target="_blank" rel="noopener noreferrer">{item.title}<ArrowUpRight size={12}/></a>:<strong>{item.title}</strong>}<small>{item.url?'Archivo disponible en el repositorio público':'Documento revisado en el checkout de desarrollo'}</small></div><code>{item.path}</code></div>)}</div></details></Reveal><Reveal className="final-cta"><div className="final-cta-orbit" aria-hidden="true"/><div><span className="mono">DE UNA PREGUNTA A UN CASO JUSTIFICADO</span><h2>Empezá por el problema.<br/><em>Conservá las razones.</em></h2><p>El dueño define propósito y límites. El agente investiga y construye. El expediente mantiene el trabajo explicable, revisable y reanudable.</p><div><a className="button hero-primary" href="#empezar">Preparar un caso<ArrowRight size={15}/></a><RepoLink className="final-repo">Ver el repositorio</RepoLink></div></div><Network size={110} strokeWidth={.5} className="final-network" aria-hidden="true"/></Reveal></section>
    </main><footer><div><Logo/><p>Una razón para cada decisión.</p></div><div className="footer-links"><a href="#metodo">El método</a><a href="#empezar">Guía de uso</a><RepoLink>GitHub</RepoLink></div><span>Presentación del desarrollo · {new Date(data.published_at).getUTCFullYear()}</span></footer>
  </>;
}

function Toolkit({tools}:{tools:string[]}){
  const [expanded,setExpanded]=useState(false);
  const commands=[{id:'init',desc:'Crear un expediente de caso.'},{id:'put',desc:'Registrar artefactos y sus referencias.'},{id:'next-task',desc:'Conocer la fase y el trabajo pendiente.'},{id:'trace',desc:'Recorrer dependencias versionadas.'},{id:'run',desc:'Aplicar y reanudar pasos declarados.'},{id:'report',desc:'Leer resultado, alcance y bloqueos.'}];
  return <section className="section toolkit-section" id="toolkit"><SectionHead number="04" eyebrow="UN MÉTODO, DOS INTERFACES" title="El agente trabaja." accent="El expediente lo conecta." description="CLI y MCP comparten el motor. El toolkit conserva artefactos, revisiones y recibos; el agente aporta el razonamiento y ejecuta las herramientas y pruebas reales."/>
    <Reveal className="toolkit-bento"><div className="architecture-card"><div className="workbench-label"><Boxes size={14}/><span>EL NÚCLEO DEL SISTEMA</span></div><div className="architecture-actors"><div><UserRound size={18}/><strong>El dueño</strong><span>Propósito y límites</span></div><div><Bot size={18}/><strong>El agente</strong><span>Indagación y ejecución</span></div></div><div className="architecture-transport"><span><Terminal size={14}/>CLI <code>organon</code></span><span><Braces size={14}/>MCP <code>organon-mcp</code></span></div><div className="architecture-arrow"><ArrowDown size={19}/></div><div className="architecture-engine"><Layers3 size={23}/><strong>Motor compartido</strong><span>Artefactos · dependencias · compuertas</span></div><div className="architecture-arrow"><ArrowDown size={18}/></div><div className="architecture-ledger"><Database size={17}/><div><strong>Ledger y runner</strong><span>Historia, checkpoints y recibos</span></div><ShieldCheck size={17}/></div></div>
      <div className="toolkit-command-card"><div className="workbench-label"><Command size={14}/><span>UN LENGUAJE PARA EL TRABAJO</span></div><h3>Dejar el siguiente paso<br/><em>a la vista.</em></h3><p>Comandos para empezar, registrar y continuar. La semántica y los controles pertenecen al mismo núcleo.</p><div className="command-list">{commands.map(item=><div key={item.id}><code>{item.id}</code><span>{item.desc}</span><ArrowUpRight size={13}/></div>)}</div><button className="text-link tools-expand" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded} aria-controls="all-tools">{expanded?'Ocultar inventario':`Ver las ${tools.length} herramientas MCP`}<ChevronDown size={13}/></button></div>
      <div className="toolkit-feature"><GitBranch size={22}/><h4>Revisar dependencias</h4><p>Las versiones nuevas pueden volver obsoletos requisitos y resultados; la reparación mantiene la historia.</p></div><div className="toolkit-feature"><ShieldCheck size={22}/><h4>Respetar compuertas</h4><p>Revisión vigente y confianza según la política del caso. Las decisiones normativas conservan su autorización.</p></div><div className="toolkit-feature"><CodeXml size={22}/><h4>Reanudar sin duplicar</h4><p>El mismo manifiesto omite pasos materializados y permite continuar desde el checkpoint persistido.</p></div>
    </Reveal><AnimatePresence>{expanded&&<motion.div id="all-tools" className="all-tools" initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}><span className="mono">IDENTIFICADORES MCP DESCUBIERTOS EN EL WHEEL</span><div>{tools.map(tool=><code key={tool}>{tool}</code>)}</div></motion.div>}</AnimatePresence>
  </section>;
}
