"""Common prospective admission budget for N/S/T/A native role calls.

This wrapper is inert until a harness uses it. Limits and protocol digest must
be explicit; no study is registered or generated by constructing it. Rendered
native prompt bytes, including repeated instructions, count toward input usage.
No credentials, environment values or provider profiles are recorded here.
"""
from contextlib import contextmanager
import fcntl
import os
from pathlib import Path
import re
import time

from specorganon.role_jobs import canonical, digest, _json, _write, _safe, JobStore
from specorganon.software_controller import executable_fingerprint
from scripts.controller_native_role import render_prompt


class StudyBudgetError(ValueError):
    pass


class CellBudget:
    def __init__(self, root, *, protocol_sha256, max_calls, max_total_input_bytes,
                 max_elapsed_seconds, transport, validate=None):
        if type(protocol_sha256) is not str or re.fullmatch('[0-9a-f]{64}', protocol_sha256) is None:
            raise StudyBudgetError('explicit immutable protocol digest required')
        if (type(max_calls) is not int or not 1 <= max_calls <= 40
                or type(max_total_input_bytes) is not int or not 1 <= max_total_input_bytes <= max_calls * 128000
                or type(max_elapsed_seconds) is not int or not 1 <= max_elapsed_seconds <= 6000):
            raise StudyBudgetError('invalid explicit common cell limits')
        self.root = _safe(root)
        self.root.mkdir(parents=True, mode=0o700, exist_ok=True)
        info = self.root.stat()
        if info.st_uid != os.geteuid() or info.st_mode & 0o022:
            raise StudyBudgetError('private owned budget journal required')
        self.transport = transport
        self.validate = validate or (lambda: None)
        policy = {'schema':1, 'protocol_sha256':protocol_sha256, 'max_calls':max_calls,
                  'max_total_input_bytes':max_total_input_bytes, 'max_elapsed_seconds':max_elapsed_seconds,
                  'max_rendered_input_bytes':128000}
        path = self.root / 'policy.json'
        with self._lock():
            if path.exists() and _json(path) != policy:
                raise StudyBudgetError('budget/protocol changed; never grow a running cell budget')
            if not path.exists(): _write(path, policy)
        self.policy = policy

    @contextmanager
    def _lock(self):
        fd = os.open(self.root / '.lock', os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW, 0o600)
        try:
            fcntl.flock(fd, fcntl.LOCK_EX)
            yield
        finally: os.close(fd)

    def _clock(self):
        clock = self.root / 'clock.json'
        if clock.exists():
            anchor = _json(clock)
            if anchor['boot_id_sha256'] != JobStore._boot_id():
                raise StudyBudgetError('admission clock changed')
            elapsed = time.monotonic() - anchor['monotonic']
            if elapsed < 0 or elapsed >= self.policy['max_elapsed_seconds']:
                raise StudyBudgetError('global cell deadline exhausted')
        else:
            _write(clock, {'epoch':time.time(),'monotonic':time.monotonic(),
                           'boot_id_sha256':JobStore._boot_id()})

    @staticmethod
    def _id(job_id):
        if type(job_id) is not str or re.fullmatch('[A-Za-z0-9][A-Za-z0-9_-]{0,63}', job_id) is None:
            raise StudyBudgetError('invalid persistent native job ID')

    def call(self, job_id, role, request):
        self._id(job_id)
        if type(role) is not str or role not in {'author','review'} or type(request) is not dict or request.get('role') != role:
            raise StudyBudgetError('native role differs from request')
        _, rendered = render_prompt(canonical(request))
        size = len(rendered.encode('utf-8'))
        binding = {'role':role, 'request_sha256':digest(canonical(request)), 'rendered_input_bytes':size}
        with self._lock():
            self.validate()
            folder = self.root / job_id
            if folder.exists():
                if not (folder / 'admission.json').exists() or _json(folder / 'admission.json') != binding:
                    raise StudyBudgetError('admitted request diverged or preparation uncertain')
                # The underlying transport validates its own closed receipt or
                # reconciles an uncertain handle. Never manufacture a packet or
                # reserve a replacement job because observation was interrupted.
                return self.transport.call(job_id, role, request)
            self._clock()
            history = [_json(p/'admission.json') for p in self.root.iterdir()
                       if p.is_dir() and (p/'admission.json').exists()]
            if len(history) >= self.policy['max_calls']:
                raise StudyBudgetError('common native call ceiling exhausted')
            if sum(h['rendered_input_bytes'] for h in history) + size > self.policy['max_total_input_bytes']:
                raise StudyBudgetError('common cumulative rendered input ceiling exhausted')
            folder.mkdir(mode=0o700)
            _write(folder / 'admission.json', binding)
            # Admission is durable before dispatch and remains consumed after
            # any provider/format failure. No inferred tokens or money appear.
            return self.transport.call(job_id, role, request)

    def measure(self, job_id, argv, files):
        self._id(job_id)
        binding = {'argv':argv, 'files_sha256':digest(canonical(files)),
                   'executable_sha256':executable_fingerprint(files, argv)}
        with self._lock():
            self.validate()
            folder = self.root / 'tests'; folder.mkdir(mode=0o700, exist_ok=True)
            path = folder / (job_id + '.json')
            if path.exists():
                if _json(path) != binding: raise StudyBudgetError('test binding changed')
                return self.transport.measure(job_id, argv, files)
            self._clock()
            history = [_json(p) for p in folder.glob('*.json')]
            if len(history) >= 2: raise StudyBudgetError('common two-test ceiling exhausted')
            if history and history[-1]['executable_sha256'] == binding['executable_sha256']:
                raise StudyBudgetError('second test requires changed executable inputs')
            _write(path, binding)
            return self.transport.measure(job_id, argv, files)

    def verify_test(self, *args, **kwargs):
        return self.transport.verify_test(*args, **kwargs)

    def summary(self):
        with self._lock():
            history = [_json(p/'admission.json') for p in self.root.iterdir()
                       if p.is_dir() and (p/'admission.json').exists()]
            return {'admitted_native_jobs':len(history),
                    'admitted_public_tests':len(list((self.root/'tests').glob('*.json'))),
                    'rendered_input_bytes':sum(h['rendered_input_bytes'] for h in history),
                    'policy':self.policy,'token_usage':None,'monetary_cost':None}
