import { useState } from 'react';
import { ArrowUpRight, Download, FlaskConical, ShieldCheck } from 'lucide-react';
import data from '../backup-results.json';
import { Reveal, SectionHead } from './Shared';
import '../backup-results.css';
import SoftwareLaboratory from './SoftwareLaboratory';

const base='/resultados/backup/';
const labels={N:'Trabajo libre',S:'Guía SDD',T:'Paquete SpecOrganon'};
type Arm=keyof typeof labels;
const arms:Arm[]=['N','S','T'];
const pct=(n:number)=>`${(n*100).toLocaleString('es-CO',{maximumFractionDigits:2,minimumFractionDigits:2})} %`;

export default function BackupResults(){
  const [stage,setStage]=useState<'1'|'2'>('2');
  const rows=data.deliveries.filter(row=>row.stage===Number(stage));
  return <section className="section backup-results" id="resultados">
    <SectionHead number="07" eyebrow="PILOTO AUTÓNOMO · 3–4 OCTUBRE 2026" title="Un experimento real." accent="Resultados que se pueden revisar." description="Codex construyó una herramienta de backups en Docker, con el MCP real en el brazo SpecOrganon. Dieciocho ejecuciones, dos etapas por ejecución y un evaluador reservado. El piloto terminó; la tesis general sigue abierta."/>
    <SoftwareLaboratory/>
    <Reveal className="backup-verdict"><FlaskConical size={25}/><div><h3>Señal funcional favorable. Método completo no demostrado.</h3><p>El paquete T obtuvo una media de 98,48 % tras el cambio de requisitos, frente a 77,27 % con la guía SDD y 54,55 % en trabajo libre. Es una comparación descriptiva de seis ejecuciones por brazo: no demuestra superioridad general ni eficacia de campo.</p><a className="text-link" href={`${base}RESULTADOS.html`}>Leer el informe completo<ArrowUpRight size={15}/></a></div></Reveal>
    <div className="backup-counts">{[['18','ejecuciones independientes'],['36','entregas evaluadas'],['84','sesiones nuevas de modelo'],['36 / 36','resultados iguales en Python limpio']].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>
    <div className="backup-design"><p><strong>Diseño:</strong> tres variantes —documentos, versiones y corrupción/interrupción— × N/S/T × dos repeticiones. Seis bloques pareados con los seis órdenes posibles. Etapa inicial: 20 comprobaciones; cambio común <code>--max-bytes</code>: 22. Contrato, calendario, evaluador e imágenes congelados antes de generar.</p><p><strong>Presupuesto:</strong> N y S, 600 s de autoría; T, 480 s de autoría + 120 s de revisión del método. Todos tuvieron hasta 120 s adicionales de revisión funcional. Codex CLI 0.160.0, modelo configurado gpt-6.1-sol, esfuerzo high. El paquete T incluye toolkit y skill; no se aísla un mecanismo filosófico puro.</p></div>
    <div className="backup-stage-controls" role="group" aria-label="Etapa de los resultados"><button aria-pressed={stage==='1'} onClick={()=>setStage('1')}>1 · Contrato inicial</button><button aria-pressed={stage==='2'} onClick={()=>setStage('2')}>2 · Cambio de requisitos</button></div>
    <div className="backup-table-wrap"><table className="backup-summary"><caption>Puntuaciones funcionales · {stage==='1'?'20':'22'} comprobaciones por entrega · n = 6 por brazo</caption><thead><tr><th scope="col">Condición</th><th scope="col">Media</th><th scope="col">Mediana</th><th scope="col">Rango</th><th scope="col">Perfectas</th></tr></thead><tbody>{arms.map(arm=>{const s=data.summary[arm][stage];return <tr key={arm}><th scope="row"><span>{arm}</span>{labels[arm]}</th><td>{pct(s.score_mean)}</td><td>{pct(s.score_median)}</td><td>{pct(s.score_min)} – {pct(s.score_max)}</td><td>{rows.filter(r=>r.arm===arm&&r.score===1).length} / 6</td></tr>;})}</tbody></table></div>
    <p className="backup-table-note">Los checks no son réplicas independientes. La adaptación se examina con los veinte checks comunes y las dos pruebas de cuota por separado. En etapa dos, T−S: +21,21 puntos de media, mediana 0 y rango −9,09 a +68,18. T−N: +43,94 puntos de media. La ventaja no fue uniforme.</p>
    <div className="backup-findings"><article><span className="mono">DOCUMENTACIÓN</span><h3>0 / 6 README en T</h3><p>Ninguna entrega inicial incluyó README. Tras el cambio: N 4/6, S 4/6, T 0/6. Puntuación perfecta + README presente: N 2/6, S 4/6, T 0/6. Esta observación posterior conserva intacto el score primario.</p></article><article><span className="mono">ADHERENCIA AL MÉTODO</span><h3>0 / 12 recorridos completos</h3><p>Ningún ledger T tuvo las nueve fases aceptadas ni recibos en <code>test_execution_records</code>. Sí hubo pruebas propias por otras vías. El caso raíz del orquestador conserva 1/9 fases y una revisión de frame tardía.</p></article><article><span className="mono">INTEGRIDAD Y LÍMITES</span><h3>0 fallos críticos observados</h3><p>Sin corrupción silenciosa, mutación protegida ni evaluaciones inconclusas observadas. Recuperación tras SIGKILL en etapa dos: N 2/6, S 4/6, T 6/6. Un rechazo temprano por permisos explica varios fallos dependientes y limita la extrapolación.</p></article></div>
    <details className="backup-deliveries"><summary>Consultar las 18 entregas de esta etapa</summary><div className="backup-table-wrap"><table><thead><tr><th scope="col">Entrega</th><th scope="col">Checks</th><th scope="col">README</th><th scope="col">Fases T vigentes</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><th scope="row">{row.id}</th><td>{row.checks_passed} / {row.checks_total}</td><td>{row.readme_present?'Presente':'Ausente'}</td><td>{row.accepted_phases===null?'No aplica':`${row.accepted_phases} / 9`}</td></tr>)}</tbody></table></div><p>Los datos descargables conservan ambas etapas, cada check, diferencias pareadas, recursos informados y observaciones de método.</p></details>
    <Reveal className="backup-product"><ShieldCheck size={26}/><div><span className="mono">PRODUCTO SELECCIONADO · V1-r1-N · TRABAJO LIBRE</span><h3>Crear, verificar y restaurar backups.</h3><p>Implementación original sin reparaciones posteriores: Python 3.12 en Linux y biblioteca estándar. Pasó 22/22 comprobaciones en cada una de las tres variantes, 32 pruebas propias y el ejemplo de restauración. La selección predefinida eligió una entrega del brazo libre.</p><p>Verifica integridad SHA-256, conserva snapshots, rechaza enlaces y archivos especiales, evita sobrescrituras y aplica una cuota global. La comprobación del producto reutiliza familias y semillas conocidas; no es un nuevo holdout confirmatorio. No conserva ACL ni metadatos y no ofrece cifrado.</p><div className="backup-product-links"><a className="button hero-primary" href={`${base}backup-product.tar.gz`} download><Download size={16}/>Descargar backup</a><a className="text-link" href={`${base}product/README.html`}>Guía y límites del producto<ArrowUpRight size={14}/></a></div></div></Reveal>
    <details className="backup-limits"><summary>Entorno, incidencias, costes y qué falta comprobar</summary><p>46 de 84 sesiones terminaron por presupuesto y no informaron tokens: no se imputa cero ni se afirma ahorro monetario. Hubo cierres del host local de code-mode en dos sesiones, con sus eventos conservados; no se observaron rechazos de autenticación, cuota o API.</p><p>La revisión funcional usó código en solo lectura y evaluador sin red ni autenticación. La revisión del método permitía escritura del ledger: no se observaron ediciones de código, pero faltó una captura previa y una restricción física de escritura sobre la solución. Hashes y auditorías acreditan consistencia local, no custodia externa autenticada.</p><p>Los tiempos pequeños y el espacio son secundarios y condicionados al éxito; no prueban ventaja de rendimiento. La línea base de este piloto conservó tres fallos de auditoría por digest de pdftotext; el avance de ingeniería publicado arriba reproduce el extractor histórico en un entorno fijado, sin reescribir estos resultados. Las 83 pruebas del paquete de reproducción pasaron; esa evidencia corresponde a su alcance.</p><p>Una siguiente etapa requiere otros dominios, más repeticiones, presupuesto para completar método y documentación, documentación/adherencia puntuadas desde el protocolo y mejores controles del revisor. El objetivo original de campo y generalización no se declara cumplido.</p></details>
    <div className="backup-downloads"><h3>El resultado completo, descargable.</h3><p>Fuentes, protocolo, resultados y verificaciones. Las exportaciones públicas omiten sesiones de participantes, credenciales y rutas privadas del equipo. La distribución identifica sus archivos mediante SHA-256.</p><div>{[['RESULTADOS.html','Informe completo','Diseño, resultados, incidencias y veredicto'],['resultados.csv','36 entregas · CSV','Puntuaciones y observaciones comparables'],['analysis/results.json','Resultados · JSON','Checks, pares y recursos por etapa'],['specorganon-backup-reproduction.tar.gz','Reproducción · fuentes','Toolkit, Docker, controles y harness'],['evidencia-publica.tar.gz','Evidencia pública','Informes, auditorías y comprobaciones'],['descargas-manifest.json','Manifiesto de descargas','Hashes de paquetes y fuentes']].map(([path,title,detail])=><a key={path} href={base+path}><span><strong>{title}</strong><small>{detail}</small></span><ArrowUpRight size={17}/></a>)}</div></div>
  </section>;
}
