import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { ArrowRight, ArrowUpRight, BookOpen, Check, CircleCheck, FileText, GitBranch, Layers3, Search, ShieldCheck, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import type { ProjectData } from '../types';
import { Count, Reveal, SectionHead } from './Shared';

export default function Evidence({data}:{data:ProjectData}){
  const [caseId,setCaseId]=useState('school'),[registry,setRegistry]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState(-1);
  const dialog=useRef<HTMLDialogElement>(null), reduced=useReducedMotion();
  const chosen=data.cases.find(item=>item.id===caseId)!;
  useEffect(()=>{if(registry)dialog.current?.showModal();else dialog.current?.close();},[registry]);
  const era=data.eras[filter];
  const decisions=data.decisions.filter(item=>(!era||item.number>=era.from&&item.number<=era.to)&&(!query||`${item.id} ${item.title}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')))).reverse();
  return <section className="section evidence-section" id="evidencia">
    <SectionHead number="06" eyebrow="EL ESTADO DEL PROYECTO" title="Un MVP documentado." accent="Evidencia con su alcance." description="El corte del 1 de octubre conserva dos casos locales y la valoración C1–C5 del responsable. El nuevo piloto de backups se presenta después, con resultados favorables y adversos; no acredita por sí solo la tesis general."/>
    <Reveal className="mvp-status"><div className="mvp-status-copy"><span className="status-chip"><span className="status-dot"/>MVP TÉCNICO LOCAL DISPONIBLE</span><h3>Dos proyectos.<br/><em>El recorrido completo.</em></h3><p>Entrada de uso y reproducción escolar: nueve fases aceptadas, revisión técnica nativa separada y comandos reales. El expediente registra reanudación, replay y reapertura ante una premisa nueva.</p></div><div className="mvp-status-metrics"><div><strong><Count value={data.mvp.cases.length}/></strong><span>proyectos locales expuestos</span></div><div><strong>9 / 9</strong><span>fases aceptadas por proyecto</span></div><div><strong><Count value={data.mvp.regression_tests}/></strong><span>pruebas de regresión documentadas</span></div><div><strong>0</strong><span>eventos nuevos en replay terminal</span></div></div></Reveal>
    <Reveal className="evidence-checks">{[{icon:CircleCheck,title:'Instalación y transporte',text:`Wheel fuera del árbol; ${data.mvp.tools.length} herramientas MCP descubiertas. report y replay coinciden por CLI/MCP en los dos casos.`},{icon:GitBranch,title:'Invalidación observada',text:`Una hipótesis cambió en una copia: de ${data.mvp.invalidation.before_accepted_phases} a ${data.mvp.invalidation.after_accepted_phases} fases aceptadas. El avance injustificado fue rechazado y el original quedó intacto.`},{icon:ShieldCheck,title:'Revisión y corrección',text:'Dos rondas conservadas. Se corrigieron hallazgos del reporte y la formulación de evidencia; el resultado escolar coincide byte por byte.'}].map(item=>{const Icon=item.icon;return <article key={item.title}><Icon size={21}/><h4>{item.title}</h4><p>{item.text}</p></article>;})}</Reveal>
    <Reveal className="case-studies"><div className="subsection-heading"><div><span className="mono">CASOS DE DESARROLLO</span><h3>Distintas preguntas. Un mismo núcleo.</h3></div><span>Datos publicados · alcances declarados</span></div><div className="case-tab-row" role="tablist" aria-label="Casos documentales">{data.cases.map(item=><button key={item.id} id={`case-${item.id}`} aria-controls="case-panel" role="tab" aria-selected={caseId===item.id} onClick={()=>setCaseId(item.id)} className={caseId===item.id?'selected':''}>{caseId===item.id&&<motion.span layoutId="case-pill" className="case-pill" transition={{type:'spring',stiffness:300,damping:30}}/>}{item.title}</button>)}</div><AnimatePresence mode="wait"><motion.div key={chosen.id} className="case-story" role="tabpanel" id="case-panel" aria-labelledby={`case-${chosen.id}`} initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.22}}><div className="case-story-copy"><span className="case-subtitle">{chosen.subtitle}</span><h4>{chosen.title}</h4><p>{chosen.text}</p><div className="case-limit"><BookOpen size={14}/><div><strong>Alcance de esta evidencia</strong><p>{chosen.limit}</p></div></div></div><div className="case-story-visual"><span className="mono">EVIDENCIA DOCUMENTAL</span><strong className="case-metric">{chosen.metric}</strong><span className="case-unit">{chosen.unit}</span><CaseVisual visual={chosen.visual}/></div></motion.div></AnimatePresence></Reveal>
    <Reveal className="acceptance"><div className="subsection-heading"><div><span className="mono">VALORACIÓN PREVIA · RESPONSABLE · 1 OCTUBRE 2026</span><h3>El responsable valoró C1–C5 como completos.</h3></div><span className="acceptance-counter"><CircleCheck size={13}/>{data.metrics.criteria_met} / {data.metrics.criteria_total} completos</span></div><div className="acceptance-rows">{data.criteria.map(item=><details className="acceptance-row" key={item.number}><summary><span className="acceptance-index">C{item.number}</span><strong>{item.title}</strong><span className={`verdict ${/^cumplido(?:\s|$)/i.test(item.verdict)?'met':''}`}>{/^cumplido(?:\s|$)/i.test(item.verdict)?<Check size={11}/>:<span className="verdict-dot"/>}{item.verdict}</span><ArrowUpRight size={14}/></summary><div className="acceptance-body"><div><span className="mono">EVALUACIÓN DEL RESPONSABLE</span><p>{item.evidence}</p></div><div><span className="mono">NUEVOS CASOS DE APLICACIÓN</span><p>{item.gate}</p></div></div></details>)}</div><p className="acceptance-note">{data.assessment.statement} Esta es una valoración declarada del responsable, conservada del corte anterior. El piloto autónomo posterior no demuestra la tesis general ni el recorrido metodológico completo.</p></Reveal>
    <Reveal className="history-section"><div className="subsection-heading"><div><span className="mono">EL RECORRIDO DEL DESARROLLO</span><h3>Una historia de decisiones revisables.</h3></div><button className="text-link" onClick={()=>setRegistry(true)}>Ver {data.decisions.length} decisiones<ArrowUpRight size={14}/></button></div><div className="milestone-grid">{data.eras.map((item,index)=><article key={item.label}><span className="milestone-number">{String(index+1).padStart(2,'0')}</span><span className="mono">D-{String(item.from).padStart(3,'0')} → {item.to===999?data.decisions.at(-1)?.id:`D-${String(item.to).padStart(3,'0')}`}</span><h4>{item.title}</h4><p>{item.text}</p><button onClick={()=>{setFilter(index);setQuery('');setRegistry(true);}}>{item.count} entradas<ArrowRight size={12}/></button></article>)}</div><div className="experimental-footnote"><Layers3 size={17}/><p><strong>A/B/C:</strong> etapas, grafo revisable y portafolio por riesgos. {data.metrics.mechanical_runs} ejecuciones mecánicas sintéticas. <strong>{data.metrics.formal_executed}/{data.metrics.formal_planned} celdas formales</strong> del plan R1/R2. Estas cifras corresponden al plan histórico R1/R2. El piloto autónomo de backups N/S/T, distinto de ese plan, ya completó 18 ejecuciones y 36 entregas; sus resultados se presentan a continuación.</p></div></Reveal>
    <dialog className="registry-dialog" ref={dialog} onCancel={()=>setRegistry(false)} aria-labelledby="registry-title"><div className="registry-heading"><div><span className="mono">REGISTRO DEL CHECKOUT REVISADO</span><h3 id="registry-title">Cada elección tiene una historia.</h3></div><button onClick={()=>setRegistry(false)} aria-label="Cerrar registro"><X size={21}/></button></div><label className="registry-search"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar D-124, evidencia, revisiones…" aria-label="Buscar decisiones"/></label><div className="registry-filters"><button className={filter===-1?'selected':''} onClick={()=>setFilter(-1)}>Todas</button>{data.eras.map((item,index)=><button key={item.label} className={filter===index?'selected':''} onClick={()=>setFilter(index)}>{item.label}</button>)}</div><p className="registry-count">{decisions.length} entradas · títulos y fechas del registro original</p><div className="registry-entries">{decisions.map(item=><div key={item.id}><code>{item.id}</code><strong>{item.title}</strong><time>{item.date}</time></div>)}{!decisions.length&&<p className="empty-state">No hay decisiones que coincidan con esta búsqueda.</p>}</div><p className="registry-footer"><FileText size={12}/>Esta lista conserva el registro histórico del corte revisado. Las fuentes y los avances posteriores están publicados en la rama main del repositorio.</p></dialog>
  </section>;
}

function CaseVisual({visual}:{visual:string}){
  const reduced=useReducedMotion();
  if(visual==='bars')return <div className="school-chart" role="img" aria-label="Contraste descriptivo: base 45,10 g por persona; intervención 29,07 g por persona"><div className="school-row"><span>Base</span><motion.i initial={{scaleX:reduced?1:0}} animate={{scaleX:1}} transition={{duration:.8,ease:'easeOut'}} style={{width:'100%'}}/><strong>45,10 g</strong></div><div className="school-row"><span>Intervención</span><motion.i initial={{scaleX:reduced?1:0}} animate={{scaleX:1}} transition={{duration:.8,delay:.1,ease:'easeOut'}} style={{width:'64.46%'}}/><strong>29,07 g</strong></div><p>Períodos publicados · sin atribución causal.<br/>Kuusisto, Latva y Wilén · CC BY 4.0. Visualización derivada.</p></div>;
  if(visual==='chain')return <div className="case-chain">{['Granja','Molino','Panadería','Comercio','Consumo'].map((label,index)=><motion.span key={label} initial={reduced?false:{opacity:0,y:5}} animate={{opacity:1,y:0}} transition={{delay:index*.07}}><i>{String(index+1).padStart(2,'0')}</i>{label}</motion.span>)}<p>Reconstrucción documental de la cadena.</p></div>;
  if(visual==='loads')return <div className="mango-illustration">{['Carga 01','Carga 02','Carga 03'].map(label=><span key={label}><FileText size={17}/>{label}</span>)}<p>Observaciones separadas; discrepancia de origen conservada.</p></div>;
  if(visual==='stations')return <div className="bike-illustration"><div aria-hidden="true">{Array.from({length:48},(_,index)=><motion.i key={index} className={[8,22,39].includes(index)?'gap':''} initial={reduced?false:{opacity:0}} animate={{opacity:1}} transition={{delay:index*.012}}/>)}</div><p>Esquema de capturas y huecos; no representa su distribución estadística.</p></div>;
  return <div className="energy-formula">(0,297 + 0,115) kWh<br/><span>÷ (736 / 1000) kg</span><p>Svanes, Østergaard y Hanssen · CC BY 4.0. Derivación documental del proyecto.</p></div>;
}
