import engineering from '../dev12-engineering.json';
export default function NativeTEngineering(){
 const repo='https://github.com/stevenvo780/SpecOrganon/tree/main';
 const evidence='https://github.com/stevenvo780/SpecOrganon/blob/main/goals/method-superiority-v1/evidence/native-t-closure-dev12-01/';
 const protocol='https://github.com/stevenvo780/SpecOrganon/blob/main/goals/method-superiority-v1/development/t-native-v1/PROTOCOL.md';
 const download='/resultados/software/avance-dev12/';
 return <section aria-labelledby="avance-dev12">
  <h5 id="avance-dev12">Dev12: custodia terminal y entrada T de desarrollo</h5>
  <p><strong>0.2.0rc3.dev12 es ingeniería prospectiva parcial.</strong> Corrige cinco hallazgos conservando sus reproducciones y rechazos: F9 reverifica al auditor común antes del primer terminal; F10 exige un ciclo de vida Docker estrictamente cerrado; F11 deriva el score público de los mismos buffers verificados; CT-01 conserva esos buffers y metadatos al preparar la revisión T; TEX-01 aclara la precedencia del procedimiento prospectivo exclusivamente para N.</p>
  <div className="backup-table-wrap"><table><thead><tr><th>Control final</th><th>Resultado y alcance</th></tr></thead><tbody>
   <tr><td>Selección ampliada</td><td>{engineering.validation.selected_tests} pruebas seleccionadas aprobadas</td></tr>
   <tr><td>Docker real</td><td>{engineering.validation.actual_docker_controls} controles mecánicos con contenido y roles simulados; sin API de proveedores</td></tr>
   <tr><td>Instalación</td><td>{engineering.validation.installed_guards} controles instalados y {engineering.installation.modules} módulos byte iguales en imágenes locales</td></tr>
   <tr><td>Interfaces</td><td>CLI, MCP stdio real de {engineering.installation.mcp_stdio_tools} herramientas y Codex CLI {engineering.installation.codex_version}; sin red ni montajes de credenciales en esos controles</td></tr>
  </tbody></table></div>
  <p><strong>Los recuentos se solapan y no son generaciones nativas.</strong> Las ocho reproducciones fallidas de F9–F11 y las dos posteriores de CT-01/TEX-01 permanecen archivadas, junto a fallos intermedios de fixtures y parsing. Las pruebas finales no borran esos antecedentes.</p>
  <p>La entrada instalada <code>organon-t-native</code> y el registro prospectivo describen <strong>diez posiciones T: cuatro RangeAudit, tres LedgerFold y tres TopoPlan</strong>. El informe instalado en imagen y wheel del host terminó con <strong>exit 2: incompleto, diez sin iniciar y cero runtime creado</strong>. Se verificó el rechazo de una instalación editable y de reemplazar el registro existente. Esto comprueba bootstrap e informe, no diez intentos ejecutados ni una admisión para generarlos.</p>
  <p><strong>Revisión estática distribuida, sin aceptación del código completo.</strong> Se conservan dos rechazos originales de Codex, una aceptación de Gemini limitada a su partición de 16 módulos y el timeout de 600 segundos de la revisión completa. Las dos revisiones delta posteriores de Codex aceptaron sus correcciones dentro del alcance asignado, sin hallazgos abiertos identificados en esas deltas. Los 46 módulos conservados coinciden con sus hashes anteriores y los dos modificados se revisaron en las deltas; esta cobertura no equivale a una aceptación completa de los 48 módulos.</p>
  <p>Los ocho trabajos de ingeniería están terminales. El rechazo de dev11 por F9–F11 permanece como corte histórico; dev12 corrige mecanismos prospectivamente y no cambia los resultados cerrados. La custodia de hashes presupone el host/daemon de confianza y no prueba la verdad externa ni el contenido semántico del auditor. La proyección textual conserva la semántica UTF-8 errors=replace: no se afirma reversibilidad de bytes no UTF-8.</p>
  <p><strong>Cero nuevas generaciones nativas. Sin admisión T, versión completa congelada, calificación, competencia ni superioridad.</strong> common_complete y F externo son null. Los originales dev7/dev8 permanecen intactos y sin reemplazos; la meta sigue activa. El transporte nuevo no migra silenciosamente journals anteriores.</p>
  <p><a href={repo}>Repositorio compartible en main</a> · <a href={protocol}>Protocolo prospectivo T</a> · <a href={evidence+'README.md'}>Informe y límites</a> · <a href={evidence+'engineering-receipt.json'}>Recibo final</a> · <a href={evidence+'final-2-installed-source-pins.json'}>48 módulos instalados</a> · <a href={evidence+'independent-review-aggregate.json'}>Revisiones y alcances</a> · <a href={evidence+'cut2-installed-T-report.receipt.json'}>Informe instalado sin generación</a> · <a href={evidence+'SHA256SUMS'}>211 archivos sellados</a></p>
  <p>Descargas del corte parcial: <a href={download+'informe.md'} download>informe</a> · <a href={download+'ingenieria.json'} download>recibo</a> · <a href={download+'fuentes-instaladas.json'} download>pins</a> · <a href={download+'revisiones-alcance.json'} download>revisiones agregadas</a> · <a href={download+'rechazo-particion-T.json'} download>rechazo T</a> · <a href={download+'rechazo-particion-neutral.json'} download>rechazo custodia</a> · <a href={download+'revision-particion-Gemini.json'} download>partición Gemini</a> · <a href={download+'revision-delta-T.json'} download>delta T</a> · <a href={download+'revision-delta-neutral.json'} download>delta custodia</a> · <a href={download+'revision-completa-timeout.json'} download>timeout completo</a> · <a href={download+'descargas-sha256.json'}>SHA-256</a>. Las 107 descargas históricas y sus once manifiestos conservan sus bytes; se agregan diez descargas y un manifiesto independiente.</p>
  <p>Las imágenes y el wheel dev12 son locales de ingeniería. No hay nueva release pública ni registry; el último wheel público sigue en dev5.</p>
 </section>;
}
