import engineering from '../dev11-engineering.json';
export default function WholeAttemptEngineering(){
 const repo='https://github.com/stevenvo780/SpecOrganon/tree/main';
 const base='https://github.com/stevenvo780/SpecOrganon/blob/main/goals/method-superiority-v1/evidence/whole-attempt-recovery-dev11-01/';
 const download='/resultados/software/avance-dev11/';
 const review=engineering.independent_static_review;
 return <section aria-labelledby="avance-dev11">
 <h5 id="avance-dev11">Dev11: recuperación de fallos cerrados y presupuesto completo</h5>
 <p><strong>0.2.0rc3.dev11 es ingeniería prospectiva parcial.</strong> El transporte conserva pruebas negativas de ejecución cerrada: salida no cero, timeout, truncamiento u OOM. La recuperación verifica identidad, entrada, fuentes, argv y streams originales sin preparar ni arrancar otra llamada. N/S/T conservan la misma reserva y sus contadores; un fallo no se convierte en respuesta aceptada, tokens o readiness.</p>
 <p>El presupuesto original de <strong>6000 segundos de CLOCK_BOOTTIME</strong> comienza antes de preparar el intento. Incluye suspensión y conserva el binding al reanudar: no renueva los 6000 segundos. Reserva 60 segundos para limpieza, exige preparación mínima de 90 y acota controles individuales a 15. La política exige impedir despacho y readiness ante un host/boot distinto, proceso dueño muerto o resultado incierto del SO/daemon; los pendientes de la revisión se conservan abajo. La limpieza acotada de seguridad no acredita cierre exitoso.</p>
 <p>La observación pública funcional tiene su intención y reloj anteriores a la fábrica real, con timeout como máximo 120 segundos; su tiempo integra el total del driver. No renueva el reloj de generación, no habilita readiness y no representa F reservado.</p>
 <div className="backup-table-wrap"><table><thead><tr><th>Control del corte corregido</th><th>Resultado con alcance</th></tr></thead><tbody>
 <tr><td>Selección ampliada</td><td>425 pruebas seleccionadas aprobadas</td></tr>
 <tr><td>Docker real</td><td>16 controles mecánicos con autores/proveedores simulados y perfil temporal vacío</td></tr>
 <tr><td>Instalación</td><td>70 controles instalados; 46 módulos byte iguales en ambas imágenes locales</td></tr>
 <tr><td>Interfaces reales</td><td>CLI, MCP stdio de 24 herramientas y Codex CLI 0.160.0; sin inferencias ni montajes de credenciales</td></tr>
 </tbody></table></div>
 <p><strong>Los recuentos se solapan y no son intentos nativos.</strong> Los recibos review-corrected acreditan el corte corregido; los probes preliminares permanecen históricos y no acreditan bytes posteriores. Las imágenes son locales, sin registry ni wheel público dev11. El último wheel público sigue siendo dev5.</p>
 <p>La revisión independiente original de Codex <strong>rechazó el primer corte con ocho hallazgos</strong>; sus reproducciones estáticas, correcciones y regresiones permanecen visibles. El trabajo de Gemini sobre dos archivos terminó por timeout de 900 segundos; el padre corrigió el fixture y verificó sus resultados, sin convertir ese timeout en éxito.</p>
 <p><strong>Revisión del corte corregido: {review.correction_review_status==='terminal_reject_component_cut'?'rechazo con tres hallazgos nuevos pendientes':review.correction_review_status}.</strong> La aceptación independiente del corte actual {review.current_cut_independent_acceptance?'consta sólo en el alcance expresado por su recibo':'sigue sin evidencia'}. La revisión anterior no acepta automáticamente los bytes corregidos.</p>
 <p>El revisor reconoce F1–F8 resueltos estáticamente y conserva <strong>F9–F11 abiertos</strong>. La revisión fue estática: sus reproducciones propuestas no se ejecutaron, no es una revisión completa del producto ni autoriza calificación.</p>
 <div className="backup-table-wrap"><table><thead><tr><th>Hallazgo nuevo</th><th>Severidad</th><th>Predicción estática pendiente</th></tr></thead><tbody>{review.new_findings.map(finding=><tr key={finding.id}><td>{finding.id}</td><td>{finding.severity==='high'?'alta':'media'}</td><td>{finding.title}</td></tr>)}</tbody></table></div>
 <p><strong>Sin admisión T nativa, versión completa congelada, calificación, competencia ni superioridad.</strong> Cero generaciones nativas nuevas y cero sujetos reservados. common_complete y F externo son null. Los seis originales dev8 mantienen cuatro fallidos y dos review_ready, con 648 comprobaciones públicas descriptivas, sin participante T ni reemplazos. La goal continúa ACTIVE.</p>
 <p><a href={repo} target="_blank" rel="noopener noreferrer">Repositorio compartible en main</a> · <a href={base+'README.md'}>Informe y límites</a> · <a href={base+'engineering-receipt.json'}>Recibo de ingeniería</a> · <a href={base+'recovery-review-original.json'}>Rechazo original</a> · <a href={base+'correction-review-source-pins.json'}>Fuentes de revisión</a> · <a href={base+'review-corrected-installed-source-pins.json'}>46 módulos instalados</a> · <a href={base+'SHA256SUMS'}>Manifiesto de evidencia</a></p>
 <p>Descargas del corte parcial: <a href={download+'informe.md'} download>informe</a> · <a href={download+'ingenieria.json'} download>recibo</a> · <a href={download+'fuentes-instaladas.json'} download>pins</a> · <a href={download+'rechazo-original.json'} download>rechazo original</a> · <a href={download+'docker-mecanico.json'} download>controles Docker</a> · <a href={download+'instalacion.json'} download>instalación</a> · <a href={download+'escritor-timeout.json'} download>timeout del escritor</a> · <a href={download+'revision-correcciones.json'} download>rechazo del corte corregido</a> · <a href={download+'descargas-sha256.json'}>SHA-256</a>. Las 99 descargas históricas y sus diez manifiestos permanecen intactos.</p>
 </section>;
}
