import { ArrowUpRight, FlaskConical } from 'lucide-react';
import data from '../software-results.json';
import SoftwareCampaign from './SoftwareCampaign';

export default function SoftwareLaboratory(){
  return <article className="software-laboratory" id="software-autonomo" aria-labelledby="software-lab-title">
    <div className="software-lab-header"><FlaskConical size={22}/><div><p className="eyebrow">HITO LOCAL DE SOFTWARE · {data.comparison_v3.F_evaluated?'RESULTADOS DEL PROTOCOLO':'INGENIERÍA EN PROGRESO'}</p><h3 id="software-lab-title">Software autónomo: resultados y límites.</h3></div><span className="software-lab-status">{data.comparison_v3.F_evaluated?'Campaña cerrada':'Goal activa'}</span></div>
    <p>La campaña conserva entregas de nueve fases con revisión separada y pruebas reales. {data.comparison_v3.F_evaluated?'La comparación de tres tareas y dos familias cerró las 42 celdas originales y su evaluación reservada, conservando también los resultados adversos. Este es el informe del hito local de software; la tesis general sigue sin demostrar.':'La comparación de tres tipos de tarea y dos familias sigue su protocolo registrado. La goal todavía no está cumplida.'}</p>
    <SoftwareCampaign/>
    <h4>Ensayos previos: cierres y límites conservados</h4>
    <div className="backup-table-wrap"><table><caption>{data.trials.length} intentos nuevos de ingeniería · independientes del piloto histórico</caption><thead><tr><th scope="col">Caso</th><th scope="col">Fases aceptadas</th><th scope="col">Llamadas intentadas</th><th scope="col">Pruebas de entrega</th><th scope="col">Veredicto</th></tr></thead><tbody>{data.trials.map(trial=><tr key={trial.name}><th scope="row">{trial.name}</th><td>{trial.accepted_phases} / {trial.total_phases}</td><td>{trial.attempted_calls}</td><td>{trial.test_executions}</td><td>{trial.status}</td></tr>)}</tbody></table></div>
    <p><strong>Qué funciona:</strong> el entorno Docker fijado reproduce el extractor histórico conservando su control de integridad; la instalación limpia CLI/MCP pasó sus comprobaciones y las consultas no cambiaron el ledger. Pasaron 17 regresiones nuevas de contexto. Los controles C5–C8 comprobaron bloqueos y recuperación con contenidos sintéticos y ejecución Docker/SIGKILL real.</p>
    <p><strong>Qué falta:</strong> ninguno de estos intentos entregó un programa. IntervalDesk llegó a siete fases aceptadas por un revisor Gemini separado del autor Codex; su construcción agotó los 180 segundos. Se conservan el timeout, las detenciones previas y el presupuesto original, sin sustituirlos por una victoria.</p>
    <h4>Candidato de ingeniería 0.2.0rc1: instalado y comprobado</h4>
    <p>El controlador schema8 explicita los campos de evidencia y diagnostica referencias obsoletas sin reparar argumentos ni aceptar fases automáticamente. Muse Code pidió correcciones y después aceptó el cambio; sus revisiones fueron de texto y no ejecutaron tests. Pasaron <strong>84 controles de fuentes y 68 controles del wheel instalado</strong>. Dos builds locales produjeron un wheel con el mismo hash.</p>
    <p>En la instalación nueva se descubrieron 24 herramientas MCP y se ejercieron 15 operaciones por CLI y 15 por MCP stdio real, con rechazo de entradas inválidas, replay y reanudación tras SIGKILL. También pasó la extracción con pdftotext fijado y el rechazo de pins falsos. <strong>Las nueve fases de este smoke histórico usan fixtures sintéticos; no cuentan como entregas autónomas.</strong> Los fallos previos de preparación de fixtures se conservan en el informe.</p>
    <h4>LotLedger: fuentes aceptadas, ensayo real cerrado sin entrega</h4>
    <p>Muse revisó las 49 fuentes completas y aceptó congelarlas después de las correcciones. Pasaron <strong>118 controles herméticos y 38 controles del evaluador con 33 sujetos Docker reales</strong>. Son contenidos sintéticos para comprobar el instrumento, no una entrega. Se preservaron las 60 recetas originales y todas sus ampliaciones hasta una matriz finita de 80; no prueban corrección universal. Las seis observaciones de primitivas SQLite tampoco son una baseline del programa.</p>
    <p>Con el registro congelado antes de generar, Codex redactó frame y Gemini 3.8 Flash lo aceptó: <strong>1/9 fases, 3/40 llamadas</strong>. La crítica de Codex produjo cinco artefactos: la respuesta aportaba 5.731 bytes, pero el motor almacenaba 6.697 bytes con metadatos frente al límite de 6.000. La regla de parada cerró la identidad, sin aumentar el techo, reparar el caso ni reiniciarlo.</p>
    <p>No hubo programa ni tests de entrega: <strong>0/80 por ausencia contractual, con cero invocaciones reservadas</strong>. La reconstrucción offline del tamaño no modificó el ledger ni se devolvió a autores. Los <a href="/resultados/software/lotledger-uso-declarado.json">contadores reportados por Codex y Gemini</a> se conservan por proveedor; no verifican facturación, débito de cuota ni equivalencia entre categorías. El coste monetario sigue desconocido.</p>
    <p>FractionMix, PolicyPick y ListPatch se eligieron antes del resultado de LotLedger. El registro posterior de v3 se presenta arriba; este ensayo permanece cerrado y no se reconstruye retrospectivamente para convertirlo en una entrega.</p>
    <div className="software-lab-downloads"><a className="text-link" href="/resultados/software/lotledger-v1.json">LotLedger: cierre y veredicto<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/lotledger-controles.json">Controles técnicos y límites<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/lotledger-evidencia-publica.zip" download>LotLedger: evidencia pública<ArrowUpRight size={15}/></a></div>
    <h4>CSVShape: nuevo intento prerregistrado, cierre fallido</h4>
    <p>Con Gemini 3.8 Flash como autor y Codex como revisor separado, aceptó <strong>dos de nueve fases</strong> y consumió ocho llamadas. En study, Codex rechazó la fundamentación del indicador y la separación de sus criterios. La corrección añadió evidencia observada y modificó el protocolo, pero dejó una dependencia a la versión anterior y usó un campo de colección que el motor no reconoce. Los dos intentos de autor permitidos en esa fase se agotaron; la identidad quedó cerrada.</p>
    <p>Se habían congelado 179 fuentes, 48 recetas, roles y presupuesto antes de generar. No llegó a build ni entregó programa: <strong>48 fallos contractuales por ausencia de programa, con cero invocaciones reservadas</strong>. Las comprobaciones del controlador, los dos sujetos Docker de control y los seis probes públicos del parser estándar son evidencia de infraestructura; no cumplen la entrega. Las revisiones previas del protocolo no predijeron una ejecución completa.</p>
    <p>Los CLI declararon uso de tokens por proveedor en las ocho llamadas; se conserva en <a href="/resultados/software/csvshape-uso-declarado.json">el registro de uso declarado</a>. Estos contadores no verifican facturación ni débito de cuota, y no se suman las categorías de razonamiento a los tokens de salida. El coste monetario sigue desconocido.</p>
    <h4>Campaña histórica02: detenida según el protocolo</h4>
    <p>Se congelaron contratos, evaluador, rúbricas, orden, cuentas y presupuesto antes de generar: 24 celdas principales y cuatro de ablación, RoutePlan/TreeMap y Codex/Gemini. <strong>Seis celdas fallaron durante generación, una quedó inconclusa por timeout nativo y 21 no se iniciaron.</strong> La regla de parada impide reiniciar esta campaña. Ninguna celda completó su entrega o las nueve fases.</p>
    <div className="backup-table-wrap"><table><caption>Resultados reservados de entregas parciales · sin ganador comparativo</caption><thead><tr><th scope="col">Celda</th><th scope="col">Cierre de generación</th><th scope="col">Casos: pasan / fallan / inconclusos</th></tr></thead><tbody>{data.comparison.rows.map(row=><tr key={row.id}><th scope="row">{row.id}</th><td>{row.status==='failed'?'Fallida':'Infraestructura inconclusa'}</td><td>{row.functional ? `${row.functional.pass} / ${row.functional.fail} / ${row.functional.inconclusive} de ${row.functional.denominator}` : 'Sin medición'}</td></tr>)}</tbody></table></div>
    <p>Las filas sin programa fallan por ausencia contractual. Los dos programas parciales se evaluaron después de detener generación: no son entregas aceptadas. Seis invocaciones quedaron inconclusas porque el evaluador rechazó sus identificadores; sus resultados no se sustituyen por reintentos. Falta la revisión final de documentación y adherencia en todas las celdas. No se calcula un ganador ni un efecto causal.</p>
    <p>TreeMap con SpecOrganon aceptó frame, recibió un rechazo sustantivo de critique y redactó una corrección. La aprobación de la norma y esa revisión agotaron el límite conjunto de dos intervenciones; la corrección quedó sin revisar. TreeMap libre ejecutó nueve tests propios con dos fallos; la llamada de reparación agotó 180 segundos sin respuesta válida y detuvo la campaña.</p>
    <details><summary>Límites y siguiente trabajo</summary><ul>{data.remaining.map(item=><li key={item}>{item}</li>)}</ul><p>Los 30 inputs congelados, resultados y ledgers del piloto anterior permanecen intactos. Estos avances no prueban superioridad general ni eficacia de campo. Costes o tokens no observados siguen siendo desconocidos. Las etiquetas del modo local no autentican identidades ni custodia externa.</p></details>
    <div className="software-lab-downloads"><a className="text-link" href="/resultados/software/avance.json">Estado y veredictos · JSON<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/campana-02.json">Campaña detenida · JSON<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/csvshape-v1.json">CSVShape: cierre fallido · JSON<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/evidencia-publica.zip" download>Contratos y evidencia pública<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/candidato-0.2.0rc1.json">Instalación candidata · informe<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/specorganon-0.2.0rc1-py3-none-any.whl" download>Wheel 0.2.0rc1<ArrowUpRight size={15}/></a><a className="text-link" href="/resultados/software/specorganon-software-candidate-0.2.0rc1.zip" download>Candidato: fuentes e instrucciones<ArrowUpRight size={15}/></a></div>
  </article>;
}
